import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedde7b/widgets/LOGINWidget1.dart';
import 'package:flutterapp/figma/undefinedde7b/widgets/Rectangle2Widget7.dart';

/* Frame Button
    Autogenerated by FlutLab FTF Generator
  */
class ButtonWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/HALLOloginWidget'),
      child: Container(
        width: 167.0,
        height: 52.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 1.0;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 167.0;
                    if (scaleX < percentWidth) {
                      scaleX = percentWidth;
                    }

                    double percentHeight = 1.0;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 52.0;
                    if (scaleY < percentHeight) {
                      scaleY = percentHeight;
                    }

                    return Stack(children: [
                      Transform(
                        transform: Matrix4(scaleX, 0, 0, 0, 0, scaleY, 0, 0, 0,
                            0, 1, 0, 0, 0, 0, 1),
                        alignment: Alignment.topLeft,
                        child: Rectangle2Widget7(),
                      )
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    double percentWidth = 0.23952095808383234;
                    double scaleX =
                        (constraints.maxWidth * percentWidth) / 40.0;
                    if (scaleX < percentWidth) {
                      scaleX = percentWidth;
                    }

                    double percentHeight = 0.28846153846153844;
                    double scaleY =
                        (constraints.maxHeight * percentHeight) / 15.0;
                    if (scaleY < percentHeight) {
                      scaleY = percentHeight;
                    }

                    return Stack(children: [
                      Transform(
                        transform: Matrix4(
                            scaleX,
                            0,
                            0,
                            0,
                            0,
                            scaleY,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            constraints.maxWidth * 0.3772455089820359,
                            constraints.maxHeight * 0.36538461538461536,
                            0,
                            1),
                        alignment: Alignment.topLeft,
                        child: LOGINWidget1(),
                      )
                    ]);
                  }),
                )
              ]),
        ),
      ),
    );
  }
}
