import 'package:flutter/material.dart';

/* Rectangle FAVPNG_google-logo-google-account-g-suite-google-images-google-search_Qt26Y8zG 1
    Autogenerated by FlutLab FTF Generator
  */
class FAVPNG_googlelogogoogleaccountgsuitegoogleimagesgooglesearch_Qt26Y8zG1Widget1
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 36.0,
      height: 36.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/fe6d172f7873c291b9b6ec4674b68578cd210819.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/fe6d172f7873c291b9b6ec4674b68578cd210819.png",
          color: null,
          fit: BoxFit.cover,
          width: 36.0,
          height: 36.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
