import 'package:flutter/material.dart';

/* Text Forgot Password?
    Autogenerated by FlutLab FTF Generator
  */
class ForgotPasswordWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Forgot Password?''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.1000000146719127,
        fontSize: 13.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.26, */
      ),
    );
  }
}
