import 'package:flutter/material.dart';

/* Text please enter your google’s account to continue using our app.
    Autogenerated by FlutLab FTF Generator
  */
class PleaseenteryourgooglesaccounttocontinueusingourappWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''please enter your google’s account to 
continue using our app.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Comfortaa',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.195, */
      ),
    );
  }
}
