import 'package:flutter/material.dart';
import 'package:flutterapp/figma/welcomepagewidget/widgets/Welcomepage1Widget.dart';

/* Frame Welcome Page
    Autogenerated by FlutLab FTF Generator
  */
class WelcomePageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/HalamanUtamaWidget'),
      child: Container(
        width: 375.0,
        height: 812.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Container(
                  width: null,
                  height: null,
                  decoration: BoxDecoration(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                  child: null,
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 375.0,
                  height: 812.0,
                  child: Welcomepage1Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
