import 'package:flutter/material.dart';

/* Rectangle welcome page 1
    Autogenerated by FlutLab FTF Generator
  */
class Welcomepage1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 812.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/9881928d18837e04ea3fb4da10c1432991db71e3.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/9881928d18837e04ea3fb4da10c1432991db71e3.png",
          color: null,
          fit: BoxFit.cover,
          width: 375.0,
          height: 812.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
