import 'package:flutter/material.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/LoginWidget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/YoualreadyhaveanaccountWidget.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class Group1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 274.0,
      height: 15.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 229.0,
            height: 15.0,
            child: YoualreadyhaveanaccountWidget(),
          ),
          Positioned(
            left: 234.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 40.0,
            height: 15.0,
            child: LoginWidget(),
          )
        ]),
      ),
    );
  }
}
