import 'package:flutter/material.dart';

/* Text or login with email
    Autogenerated by FlutLab FTF Generator
  */
class OrloginwithemailWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''or login with email''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.1,
        fontSize: 15.0,
        fontFamily: 'Lato',
        fontWeight: FontWeight.w700,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.3, */
      ),
    );
  }
}
