import 'package:flutter/material.dart';

/* Text please login or sign up to continue using our app.
    Autogenerated by FlutLab FTF Generator
  */
class PleaseloginorsignuptocontinueusingourappWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''please login or sign up to continue 
using our app.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 14.0,
        fontFamily: 'Lato',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.3333333432674408, */
      ),
    );
  }
}
