import 'package:flutter/material.dart';

/* Rectangle Tubes 1
    Autogenerated by FlutLab FTF Generator
  */
class Tubes1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 71.0,
      height: 79.0,
      decoration: BoxDecoration(
        image: DecorationImage(
          image: ExactAssetImage(
            "assets/images/9a26348222528819f67b9b55a16b479839341931.png",
          ),
          fit: BoxFit.cover,
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Image.asset(
          "assets/images/9a26348222528819f67b9b55a16b479839341931.png",
          color: null,
          fit: BoxFit.cover,
          width: 71.0,
          height: 79.0,
          colorBlendMode: BlendMode.dstATop,
        ),
      ),
    );
  }
}
