import 'package:flutter/material.dart';

/* Text WELCOME
    Autogenerated by FlutLab FTF Generator
  */
class WELCOMEWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''WELCOME''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 48.0,
        fontFamily: 'Lato',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.3333333432674408, */
      ),
    );
  }
}
