import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Vector Ellipse
    Autogenerated by FlutLab FTF Generator
  */
class EllipseWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 10.434782981872559,
      height: 6.521739482879639,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeMiterLimit: null,
          strokeCap: null,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M0 6.52174L-0.5 6.52174L-0.5 7.02174L0 7.02174L0 6.52174ZM10.4348 6.52174L10.4348 7.02174L10.9348 7.02174L10.9348 6.52174L10.4348 6.52174ZM0.5 5.21739C0.5 2.61205 2.61205 0.5 5.21739 0.5L5.21739 -0.5C2.05976 -0.5 -0.5 2.05976 -0.5 5.21739L0.5 5.21739ZM5.21739 0.5C7.82273 0.5 9.93478 2.61205 9.93478 5.21739L10.9348 5.21739C10.9348 2.05976 8.37502 -0.5 5.21739 -0.5L5.21739 0.5ZM-0.5 5.21739L-0.5 6.52174L0.5 6.52174L0.5 5.21739L-0.5 5.21739ZM0 7.02174L10.4348 7.02174L10.4348 6.02174L0 6.02174L0 7.02174ZM10.9348 6.52174L10.9348 5.21739L9.93478 5.21739L9.93478 6.52174L10.9348 6.52174Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    );
  }
}
