import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* Ellipse Ellipse
    Autogenerated by FlutLab FTF Generator
  */
class EllipseWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 7.826148986816406,
      height: 7.82608699798584,
      child: SvgWidget(painters: [
        SvgPathPainter.stroke(
          1.0,
          strokeMiterLimit: null,
          strokeCap: StrokeCap.square,
          strokeJoin: StrokeJoin.miter,
        )
          ..addPath(
              'M7.32615 3.91304C7.32615 5.79801 5.79807 7.32609 3.91307 7.32609L3.91307 8.32609C6.35034 8.32609 8.32615 6.3503 8.32615 3.91304L7.32615 3.91304ZM3.91307 7.32609C2.02808 7.32609 0.5 5.79801 0.5 3.91304L-0.5 3.91304C-0.5 6.3503 1.4758 8.32609 3.91307 8.32609L3.91307 7.32609ZM0.5 3.91304C0.5 2.02808 2.02808 0.5 3.91307 0.5L3.91307 -0.5C1.4758 -0.5 -0.5 1.47578 -0.5 3.91304L0.5 3.91304ZM3.91307 0.5C5.79807 0.5 7.32615 2.02808 7.32615 3.91304L8.32615 3.91304C8.32615 1.47578 6.35034 -0.5 3.91307 -0.5L3.91307 0.5Z')
          ..color = Color.fromARGB(255, 0, 0, 0),
      ]),
    );
  }
}
