import 'package:flutter/material.dart';

/* Text FIND ANYTHING YOU NEED FOR YOUR PET’S
    Autogenerated by FlutLab FTF Generator
  */
class FINDANYTHINGYOUNEEDFORYOURPETSWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''FIND ANYTHING 
YOU NEED FOR 
YOUR PET’S''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 36.0,
        fontFamily: 'Lato',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.3333333432674408, */
      ),
    );
  }
}
