import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined2c62/widgets/UnionWidget8.dart';

/* Frame 40 / Toolbar / Comment
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab40ToolbarCommentWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.0,
      height: 40.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 10.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 18.0,
            height: 16.0,
            child: UnionWidget8(),
          )
        ]),
      ),
    );
  }
}
