import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined2c62/widgets/UnionWidget6.dart';

/* Frame 40 / Toolbar / search
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab40ToolbarsearchWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.0,
      height: 40.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 12.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 15.853553771972656,
            height: 15.853553771972656,
            child: UnionWidget6(),
          )
        ]),
      ),
    );
  }
}
