import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined2c62/widgets/EllipseWidget3.dart';
import 'package:flutterapp/figma/undefined2c62/widgets/EllipseWidget2.dart';

/* Group person
    Autogenerated by FlutLab FTF Generator
  */
class PersonWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 10.434782981872559,
      height: 15.00001049041748,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 8.478271484375,
            right: null,
            bottom: null,
            width: 10.434782981872559,
            height: 6.521739482879639,
            child: EllipseWidget2(),
          ),
          Positioned(
            left: 1.304443359375,
            top: 4.547473508864641e-13,
            right: null,
            bottom: null,
            width: 7.826148986816406,
            height: 7.82608699798584,
            child: EllipseWidget3(),
          )
        ]),
      ),
    );
  }
}
