import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget6 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.853553771972656,
      height: 15.853553771972656,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M12 6.5C12 9.53757 9.53757 12 6.5 12C3.46243 12 1 9.53757 1 6.5C1 3.46243 3.46243 1 6.5 1C9.53757 1 12 3.46243 12 6.5ZM10.7291 11.4362C9.59234 12.411 8.11495 13 6.5 13C2.91015 13 0 10.0899 0 6.5C0 2.91015 2.91015 0 6.5 0C10.0899 0 13 2.91015 13 6.5C13 8.11495 12.411 9.59234 11.4362 10.7291L15.8536 15.1464L15.1464 15.8536L10.7291 11.4362Z')
          ..color = Color.fromARGB(204, 0, 0, 0),
      ]),
    );
  }
}
