import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined2c62/widgets/WifiWidget6.dart';

/* Frame Wifi
    Autogenerated by FlutLab FTF Generator
  */
class WifiWidget7 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 21.0,
      height: 15.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: null,
            top: 1.3333333730697632,
            right: 3.000000238418579,
            bottom: null,
            width: 15.333333015441895,
            height: 11.0,
            child: WifiWidget6(),
          )
        ]),
      ),
    );
  }
}
