import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedc690/widgets/WifiWidget9.dart';
import 'package:flutterapp/figma/undefinedc690/widgets/CellularConnectionWidget9.dart';
import 'package:flutterapp/figma/undefinedc690/widgets/BatteryWidget4.dart';

/* Frame Connections
    Autogenerated by FlutLab FTF Generator
  */
class ConnectionsWidget4 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 68.0,
      height: 16.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: null,
            top: 2.0,
            right: 0.0,
            bottom: null,
            width: 25.0,
            height: 12.0,
            child: BatteryWidget4(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 0.3088235294117647;

              double height = constraints.maxHeight * 0.9375;

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.29411764705882354,
                      constraints.maxHeight * 0.0625,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: WifiWidget9(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: null,
            top: 2.0,
            right: 50.0,
            bottom: null,
            width: 18.0,
            height: 12.0,
            child: CellularConnectionWidget9(),
          )
        ]),
      ),
    );
  }
}
