import 'package:flutter/material.dart';

/* Text DON’t have an account?
    Autogenerated by FlutLab FTF Generator
  */
class DONthaveanaccountWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''DON’t have an account? ''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w900,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.52, */
      ),
    );
  }
}
