import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedc690/widgets/RegisterWidget3.dart';
import 'package:flutterapp/figma/undefinedc690/widgets/DONthaveanaccountWidget.dart';

/* Group Group 1
    Autogenerated by FlutLab FTF Generator
  */
class Group1Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 248.0,
      height: 15.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 178.0,
            height: 15.0,
            child: DONthaveanaccountWidget(),
          ),
          Positioned(
            left: 183.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 65.0,
            height: 15.0,
            child: RegisterWidget3(),
          )
        ]),
      ),
    );
  }
}
