import 'package:flutter/material.dart';

/* Text Register
    Autogenerated by FlutLab FTF Generator
  */
class RegisterWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefinedbe6f'),
      child: Text(
        '''Register''',
        overflow: TextOverflow.visible,
        textAlign: TextAlign.center,
        style: TextStyle(
          height: 1.171875,
          fontSize: 13.0,
          fontFamily: 'Roboto',
          fontWeight: FontWeight.w900,
          color: Color.fromARGB(255, 6, 150, 255),
          /* letterSpacing: 0.52, */
        ),
      ),
    );
  }
}
