import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget9 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Transform(
        transform: Matrix4(1.00, -0.00, 0.00, 0.00, 0.00, 1.00, 0.00, 0.00,
            0.00, 0.00, 1.00, 0.00, 0.00, 0.00, 0.00, 1.00),
        alignment: Alignment.topLeft,
        child: GestureDetector(
          onTap: () => Navigator.pushNamed(context, '/HalamanUtamaWidget'),
          child: Container(
            width: 17.3619441986084,
            height: 18.12293243408203,
            child: SvgWidget(painters: [
              SvgPathPainter.fill()
                ..addPath(
                    'M1.80709 6.49583L6.1959 11.3186L5.4563 11.9917L0.306242 6.33236L0 5.99583L0.306242 5.65931L5.4563 0L6.1959 0.673047L1.80709 5.49583L8.03327 5.49583C13.2085 5.49583 17.3619 10.1309 17.3619 15.6975L17.3619 18.1229L16.3619 18.1229L16.3619 15.6975C16.3619 10.5923 12.5696 6.49583 8.03327 6.49583L1.80709 6.49583Z')
                ..color = Color.fromARGB(204, 0, 0, 0),
            ]),
          ),
        ));
  }
}
