import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/StatusBarWidget2.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/Tubes2Widget2.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/HiHisyamWidget.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/CheckoutthenewproductsgroupseventsplacesandmoreWidget.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/TabBarWidget.dart';

/* Frame Menu Utama
    Autogenerated by FlutLab FTF Generator
  */
class Undefinededd2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 1683.0,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.4895833432674408, 1.0],
          colors: [
            Color.fromARGB(255, 244, 214, 160),
            Color.fromARGB(0, 244, 214, 160)
          ],
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 34.0,
            top: 675.0,
            right: null,
            bottom: null,
            width: 308.0,
            height: 333.0,
            child: Tubes2Widget2(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.5386666666666666;
              double scaleX = (constraints.maxWidth * percentWidth) / 202.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.023767082590612002;
              double scaleY = (constraints.maxHeight * percentHeight) / 40.0;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.056,
                      constraints.maxHeight * 0.0457516339869281,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: HiHisyamWidget(),
                )
              ]);
            }),
          ),
          Positioned(
            left: 21.0,
            top: 121.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 26.0,
            child: CheckoutthenewproductsgroupseventsplacesandmoreWidget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: StatusBarWidget2(),
          ),
          Positioned(
            left: 0.0,
            top: null,
            right: null,
            bottom: 0.0,
            width: 375.0,
            height: 83.0,
            child: TabBarWidget(),
          )
        ]),
      ),
    ));
  }
}
