import 'package:flutter/material.dart';
import 'package:flutterapp/figma/hallologinwidget/widgets/LoginisSuccessfullWidget.dart';
import 'package:flutterapp/figma/hallologinwidget/widgets/Tubes2Widget1.dart';

/* Frame HALLO login
    Autogenerated by FlutLab FTF Generator
  */
class HALLOloginWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefinededd2'),
      child: Container(
        width: 375.0,
        height: 812.0,
        decoration: BoxDecoration(
          gradient: LinearGradient(
            begin: Alignment(0.0, -1.0),
            end: Alignment(0.0, 0.9999999999999998),
            stops: [0.4895833432674408, 1.0],
            colors: [
              Color.fromARGB(255, 244, 214, 160),
              Color.fromARGB(0, 244, 214, 160)
            ],
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 34.0,
                  top: 239.0,
                  right: null,
                  bottom: null,
                  width: 308.0,
                  height: 333.0,
                  child: Tubes2Widget1(),
                ),
                Positioned(
                  left: 39.0,
                  top: 382.0,
                  right: null,
                  bottom: null,
                  width: 297.0,
                  height: 29.0,
                  child: LoginisSuccessfullWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
