import 'package:flutter/material.dart';

/* Text log in is Successfull!
    Autogenerated by FlutLab FTF Generator
  */
class LoginisSuccessfullWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''log in is Successfull!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 24.0,
        fontFamily: 'Lato',
        fontWeight: FontWeight.w500,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.96, */
      ),
    );
  }
}
