import 'package:flutter/material.dart';

/* Rectangle Tubes 2
    Autogenerated by FlutLab FTF Generator
  */
class Tubes2Widget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Opacity(
      opacity: 0.5,
      child: Container(
        width: 308.0,
        height: 333.0,
        decoration: BoxDecoration(
          image: DecorationImage(
            image: ExactAssetImage(
              "assets/images/9a26348222528819f67b9b55a16b479839341931.png",
            ),
            fit: BoxFit.cover,
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/9a26348222528819f67b9b55a16b479839341931.png",
            color: null,
            fit: BoxFit.cover,
            width: 308.0,
            height: 333.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
