import 'package:flutter/material.dart';

/* Rectangle Facebook Scalable Graphics Icon, Facebook logo , Facebook logo transparent background PNG clipart 2
    Autogenerated by FlutLab FTF Generator
  */
class FacebookScalableGraphicsIconFacebooklogoFacebooklogotransparentbackgroundPNGclipart2Widget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(25.5),
      child: Container(
        width: 42.0,
        height: 42.0,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(25.5),
          image: DecorationImage(
            image: ExactAssetImage(
              "assets/images/84ec03b0eb217b135f1100d3e91c2ab15e29c45d.png",
            ),
            fit: BoxFit.cover,
          ),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(25.5),
          child: Image.asset(
            "assets/images/84ec03b0eb217b135f1100d3e91c2ab15e29c45d.png",
            color: null,
            fit: BoxFit.cover,
            width: 42.0,
            height: 42.0,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    );
  }
}
