import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/FacebookScalableGraphicsIconFacebooklogoFacebooklogotransparentbackgroundPNGclipart2Widget.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/TwitterWidget1.dart';

/* Group Group 4
    Autogenerated by FlutLab FTF Generator
  */
class Group4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 56.0,
      height: 56.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 56.0,
            child: TwitterWidget1(),
          ),
          Positioned(
            left: 7.0,
            top: 7.0,
            right: null,
            bottom: null,
            width: 42.0,
            height: 42.0,
            child:
                FacebookScalableGraphicsIconFacebooklogoFacebooklogotransparentbackgroundPNGclipart2Widget(),
          )
        ]),
      ),
    );
  }
}
