import 'package:flutter/material.dart';

/* Rectangle Rectangle 2
    Autogenerated by FlutLab FTF Generator
  */
class Rectangle2Widget12 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 343.0,
      height: 52.0,
      decoration: BoxDecoration(
        border: Border.all(
          width: 2.0,
          color: Color.fromARGB(255, 0, 0, 0),
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 255, 255, 255),
          ),
          child: null,
        ),
      ),
    );
  }
}
