import 'package:flutter/material.dart';

/* Text Register
    Autogenerated by FlutLab FTF Generator
  */
class RegisterWidget10 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Login''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 36.0,
        fontFamily: 'Comfortaa',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.54, */
      ),
    );
  }
}
