import 'package:flutter/material.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/PleaseloginorsignuptocontinueusingourappWidget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/Group1Widget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/ButtonWidget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/WELCOMEWidget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/Tubes1Widget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/StatusBarWidget.dart';
import 'package:flutterapp/figma/halamanutamawidget/widgets/Group2Widget.dart';

/* Frame Halaman Utama
    Autogenerated by FlutLab FTF Generator
  */
class HalamanUtamaWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.4895833432674408, 1.0],
          colors: [
            Color.fromARGB(255, 244, 214, 160),
            Color.fromARGB(0, 244, 214, 160)
          ],
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 93.0,
            top: 307.0,
            right: null,
            bottom: null,
            width: 189.0,
            height: 34.0,
            child: PleaseloginorsignuptocontinueusingourappWidget(),
          ),
          Positioned(
            left: 104.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 167.0,
            height: 52.0,
            child: ButtonWidget(),
          ),
          Positioned(
            left: 62.0,
            top: 247.0,
            right: null,
            bottom: null,
            width: 250.0,
            height: 77.0,
            child: WELCOMEWidget(),
          ),
          Positioned(
            left: 152.0,
            top: 168.0,
            right: null,
            bottom: null,
            width: 71.0,
            height: 79.0,
            child: Tubes1Widget(),
          ),
          Positioned(
            left: 50.0,
            top: 735.0,
            right: null,
            bottom: null,
            width: 274.0,
            height: 15.0,
            child: Group1Widget(),
          ),
          Positioned(
            left: 115.0,
            top: 374.0,
            right: null,
            bottom: null,
            width: 144.0,
            height: 143.0,
            child: Group2Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: StatusBarWidget(),
          )
        ]),
      ),
    ));
  }
}
