import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/Group1Widget3.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/UnionWidget11.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/Group4Widget.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/ForgotPasswordWidget2.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/PleaseenteryourfacebooksaccounttocontinueusingourappWidget.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/ComponentWidget7.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/StatusBarWidget6.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/ButtonWidget4.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/ComponentWidget6.dart';
import 'package:flutterapp/figma/undefined6a25/widgets/RegisterWidget11.dart';

/* Frame facebook login
    Autogenerated by FlutLab FTF Generator
  */
class Undefined6a25 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 375.0,
      height: 812.0,
      decoration: BoxDecoration(
        gradient: LinearGradient(
          begin: Alignment(0.0, -1.0),
          end: Alignment(0.0, 0.9999999999999998),
          stops: [0.4895833432674408, 1.0],
          colors: [
            Color.fromARGB(255, 244, 214, 160),
            Color.fromARGB(0, 244, 214, 160)
          ],
        ),
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 104.0,
            top: 659.0,
            right: null,
            bottom: null,
            width: 167.0,
            height: 52.0,
            child: ButtonWidget4(),
          ),
          Positioned(
            left: 67.0,
            top: 727.0,
            right: null,
            bottom: null,
            width: 248.0,
            height: 15.0,
            child: Group1Widget3(),
          ),
          Positioned(
            left: 20.0,
            top: 44.0,
            right: null,
            bottom: null,
            width: 17.3619441986084,
            height: 18.12293243408203,
            child: UnionWidget11(),
          ),
          Positioned(
            left: 20.0,
            top: 87.0,
            right: null,
            bottom: null,
            width: 148.0,
            height: 40.0,
            child: RegisterWidget11(),
          ),
          Positioned(
            left: 20.0,
            top: 286.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 52.0,
            child: ComponentWidget6(),
          ),
          Positioned(
            left: 20.0,
            top: 372.0,
            right: null,
            bottom: null,
            width: 343.0,
            height: 52.0,
            child: ComponentWidget7(),
          ),
          Positioned(
            left: 255.0,
            top: 437.0,
            right: null,
            bottom: null,
            width: 127.0,
            height: 14.0,
            child: ForgotPasswordWidget2(),
          ),
          Positioned(
            left: 139.0,
            top: 79.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 56.0,
            child: Group4Widget(),
          ),
          Positioned(
            left: 20.0,
            top: 160.0,
            right: null,
            bottom: null,
            width: 268.0,
            height: 28.0,
            child: PleaseenteryourfacebooksaccounttocontinueusingourappWidget(),
          ),
          Positioned(
            left: -1.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 375.0,
            height: 44.0,
            child: StatusBarWidget6(),
          )
        ]),
      ),
    ));
  }
}
