import 'package:flutter/material.dart';

/* Text By signing up, you agree to Pet Center’s Terms of Service and Privacy Policy.
    Autogenerated by FlutLab FTF Generator
  */
class BysigningupyouagreetoPetCentersTermsofServiceandPrivacyPolicyWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''By signing up, you agree to Pet Center’s Terms of Service and Privacy Policy.''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.3846153846153846,
        fontSize: 13.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 0.0, */
      ),
    );
  }
}
