import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedbe6f/widgets/CellularConnectionWidget2.dart';

/* Frame Cellular Connection
    Autogenerated by FlutLab FTF Generator
  */
class CellularConnectionWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 18.0,
      height: 12.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: null,
            top: 0.6666666865348816,
            right: 0.3333333134651184,
            bottom: null,
            width: 17.0,
            height: 10.666666984558105,
            child: CellularConnectionWidget2(),
          )
        ]),
      ),
    );
  }
}
