import 'package:flutter/material.dart';

/* Text sign up
    Autogenerated by FlutLab FTF Generator
  */
class SignupWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''sign up''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.center,
      style: TextStyle(
        height: 1.171875,
        fontSize: 13.0,
        fontFamily: 'Roboto',
        fontWeight: FontWeight.w900,
        color: Color.fromARGB(255, 255, 255, 255),
        /* letterSpacing: 0.52, */
      ),
    );
  }
}
