import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinedbe6f/widgets/TimeWidget2.dart';

/* Frame Time
    Autogenerated by FlutLab FTF Generator
  */
class TimeWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 56.0,
      height: 23.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.3333333432674408,
            top: null,
            right: 1.6666666567325592,
            bottom: null,
            width: null,
            height: 18.0,
            child: Transform(
                transform: Matrix4(1.00, 0.00, 0.00, 0.00, 0.00, 1.00, 0.00,
                    0.00, 0.00, 0.00, 1.00, 0.00, 0.00, 3.50, 0.00, 1.00),
                alignment: Alignment.topLeft,
                child: SizedBox(
                  width: double.infinity,
                  child: TimeWidget2(),
                )),
          )
        ]),
      ),
    );
  }
}
