import 'package:flutter/material.dart';
import 'package:flutterapp/figma/group3widget/widgets/FAVPNG_googlelogogoogleaccountgsuitegoogleimagesgooglesearch_Qt26Y8zG1Widget2.dart';
import 'package:flutterapp/figma/group3widget/widgets/Ellipse2Widget2.dart';

/* Group Google
    Autogenerated by FlutLab FTF Generator
  */
class GoogleWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 56.0,
      height: 56.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 56.0,
            child: Ellipse2Widget2(),
          ),
          Positioned(
            left: 10.0,
            top: 10.0,
            right: null,
            bottom: null,
            width: 36.0,
            height: 36.0,
            child:
                FAVPNG_googlelogogoogleaccountgsuitegoogleimagesgooglesearch_Qt26Y8zG1Widget2(),
          )
        ]),
      ),
    );
  }
}
