import 'package:flutter/material.dart';
import 'package:flutterapp/figma/group3widget/widgets/Ellipse1Widget2.dart';

/* Group Twitter
    Autogenerated by FlutLab FTF Generator
  */
class TwitterWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 56.0,
      height: 56.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 56.0,
            height: 56.0,
            child: Ellipse1Widget2(),
          )
        ]),
      ),
    );
  }
}
