import 'package:flutter/material.dart';
import 'dart:ui' as ui;
import 'package:flutter/foundation.dart' show kIsWeb;

/* Rectangle Background
    Autogenerated by FlutLab FTF Generator
  */
class BackgroundWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 83.0,
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 0, 0, 0),
            offset: Offset(0.0, -0.5),
            blurRadius: 0.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          kIsWeb
              ? SizedBox.shrink()
              : ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: SizedBox(
                      width: 375.0,
                      height: 83.0,
                      child: BackdropFilter(
                          filter: ui.ImageFilter.blur(
                            sigmaX: 13.591408729553223,
                            sigmaY: 13.591408729553223,
                          ),
                          child:
                              Container(color: Colors.black.withOpacity(0.0)))),
                ),
          ClipRRect(
            borderRadius: BorderRadius.zero,
            child: Container(
              width: null,
              height: null,
              decoration: BoxDecoration(
                color: Color.fromARGB(255, 255, 255, 255),
              ),
              child: null,
            ),
          )
        ]),
      ),
    );
  }
}
