import 'package:flutter/material.dart';

/* Rectangle Capacity
    Autogenerated by FlutLab FTF Generator
  */
class CapacityWidget2 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return ClipRRect(
      borderRadius: BorderRadius.circular(1.3333333730697632),
      child: Container(
        width: 18.0,
        height: 7.333333492279053,
        decoration: BoxDecoration(
          borderRadius: BorderRadius.circular(1.3333333730697632),
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(1.3333333730697632),
          child: Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 0, 0, 0),
            ),
            child: null,
          ),
        ),
      ),
    );
  }
}
