import 'package:flutter/material.dart';

/* Text check out the new products, groups, events, places, and more!
    Autogenerated by FlutLab FTF Generator
  */
class CheckoutthenewproductsgroupseventsplacesandmoreWidget
    extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''check out the new products, groups, 
events, places, and more!''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 12.0,
        fontFamily: 'Comfortaa',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: -0.18, */
      ),
    );
  }
}
