import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/UnionWidget2.dart';

/* Frame 40 / Toolbar / search
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab40ToolbarsearchWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/Undefined2c62'),
      child: Container(
        width: 40.0,
        height: 40.0,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              children: [
                Positioned(
                  left: 12.0,
                  top: 12.0,
                  right: null,
                  bottom: null,
                  width: 15.853553771972656,
                  height: 15.853553771972656,
                  child: UnionWidget2(),
                )
              ]),
        ),
      ),
    );
  }
}
