import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/PersonWidget.dart';

/* Frame 40 / Toolbar / bell
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab40ToolbarbellWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.0,
      height: 40.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 15.0,
            top: 12.0,
            right: null,
            bottom: null,
            width: 10.434782981872559,
            height: 15.00001049041748,
            child: PersonWidget(),
          )
        ]),
      ),
    );
  }
}
