import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/UnionWidget1.dart';

/* Frame 40 / Toolbar / new
    Autogenerated by FlutLab FTF Generator
  */
class FlutLab40ToolbarnewWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 40.0,
      height: 40.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 12.0,
            top: 13.0,
            right: null,
            bottom: null,
            width: 15.55634880065918,
            height: 14.05634880065918,
            child: UnionWidget1(),
          )
        ]),
      ),
    );
  }
}
