import 'package:flutter/material.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/BackgroundWidget1.dart';
import 'package:flutterapp/figma/undefinededd2/widgets/ShapeWidget.dart';

/* Component Tab Bar
    Autogenerated by FlutLab FTF Generator
  */
class TabBarWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 375.0,
      height: 83.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double width = constraints.maxWidth * 1.0;

              double height = constraints.maxHeight * 1.0;

              return Stack(children: [
                Transform(
                  transform:
                      Matrix4(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1),
                  alignment: Alignment.topLeft,
                  child: Container(
                    width: width,
                    height: height,
                    child: BackgroundWidget1(),
                  ),
                )
              ]);
            }),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: 0.0,
            bottom: 0.0,
            width: null,
            height: null,
            child: LayoutBuilder(
                builder: (BuildContext context, BoxConstraints constraints) {
              double percentWidth = 0.36;
              double scaleX = (constraints.maxWidth * percentWidth) / 135.0;
              if (scaleX < percentWidth) {
                scaleX = percentWidth;
              }

              double percentHeight = 0.060240963855421686;
              double scaleY = (constraints.maxHeight * percentHeight) / 5.0;
              if (scaleY < percentHeight) {
                scaleY = percentHeight;
              }

              return Stack(children: [
                Transform(
                  transform: Matrix4(
                      scaleX,
                      0,
                      0,
                      0,
                      0,
                      scaleY,
                      0,
                      0,
                      0,
                      0,
                      1,
                      0,
                      constraints.maxWidth * 0.32,
                      constraints.maxHeight * 0.8433734939759037,
                      0,
                      1),
                  alignment: Alignment.topLeft,
                  child: ShapeWidget(),
                )
              ]);
            }),
          )
        ]),
      ),
    );
  }
}
