import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 15.55634880065918,
      height: 14.05634880065918,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath(
              'M0.707107 8.48528L1.77817 7.41421L1.77817 13.0563L1.77817 13.0564L1.77817 14.0563L13.7782 14.0563L13.7782 13.0564L13.7782 13.0563L13.7782 7.41421L14.8492 8.48528L15.5563 7.77817L8.48528 0.707107L7.77817 0L7.07107 0.707107L0 7.77817L0.707107 8.48528ZM2.77817 13.0563L2.77817 6.41421L7.77817 1.41421L12.7782 6.41421L12.7782 13.0563L9.77817 13.0563L9.77817 9.05638L9.77817 8.05638L5.77817 8.05638L5.77817 9.05638L5.77817 13.0563L2.77817 13.0563ZM6.77817 9.05638L6.77817 13.0563L8.77817 13.0563L8.77817 9.05638L6.77817 9.05638Z')
          ..color = Color.fromARGB(204, 0, 0, 0),
      ]),
    );
  }
}
