import 'package:flutter/material.dart';
import 'package:flutterapp/svg/svg.dart';

/* BooleanOperation Union
    Autogenerated by FlutLab FTF Generator
  */
class UnionWidget3 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 13.0,
      height: 13.0,
      child: SvgWidget(painters: [
        SvgPathPainter.fill()
          ..addPath('M7 0L6 0L6 6L0 6L0 7L6 7L6 13L7 13L7 7L13 7L13 6L7 6L7 0Z')
          ..color = Color.fromARGB(255, 255, 255, 255),
      ]),
    );
  }
}
